# Generated by Django 6.0.2 on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0010_multihospital_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmbulanceBooking',
        ),
        migrations.DeleteModel(
            name='LabBooking',
        ),
        migrations.DeleteModel(
            name='MedicineOrder',
        ),
        migrations.DeleteModel(
            name='Ambulance',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
