from django.urls import path
from .views import (
    dashboard,
    view_doctor,
    view_patient,
    view_appointment,
    delete_doctor,
    edit_doctor,
    delete_specialist,
    add_doctor,
    add_specialist,
    view_specialist,
    add_hospital,
    add_hospital_admin,
    view_hospital_admins,
    toggle_hospital_admin_status,
    reset_hospital_admin_password,
    change_admin_password,
    view_hospital,
    delete_hospital,
)

urlpatterns = [
    path("admin/", dashboard, name='admin-dashboard'),
    path("admin/view_doctor", view_doctor, name="view_doctor"),
    path("admin/view_patient", view_patient, name="view_patient"),
    path("admin/view_appoinment", view_appointment, name="view_appointment"),
    path('delete_doctor/<int:pk>/', delete_doctor, name='delete_doctor'),
    path('edit_doctor/<int:pk>/', edit_doctor, name='edit_doctor'),
    path('delete_specialist/<int:pk>/', delete_specialist, name='delete_specialist'),
    path('admin/add_doctor/', add_doctor, name='add_doctor'),
    path("admin/add_specialist/", add_specialist, name="add_specialist"),
    path("admin/view_specialist/", view_specialist, name="view_specialist"),
    path("admin/add_hospital/", add_hospital, name="add_hospital"),
    path("admin/add_hospital_admin/", add_hospital_admin, name="add_hospital_admin"),
    path("admin/view_hospital_admins/", view_hospital_admins, name="view_hospital_admins"),
    path("admin/toggle_hospital_admin_status/<int:pk>/", toggle_hospital_admin_status, name="toggle_hospital_admin_status"),
    path("admin/reset_hospital_admin_password/<int:pk>/", reset_hospital_admin_password, name="reset_hospital_admin_password"),
    path("admin/change_password/", change_admin_password, name="change_admin_password"),
    path("admin/view_hospital/", view_hospital, name="view_hospital"),
    path("delete_hospital/<int:pk>/", delete_hospital, name='delete_hospital'),
]
